pref("extensions.abprime.currentVersion", "0.0");
pref("extensions.abprime.enabled", true);
pref("extensions.abprime.frameobjects", true);
pref("extensions.abprime.fastcollapse", false);
pref("extensions.abprime.showinstatusbar", false);
pref("extensions.abprime.detachsidebar", false);
pref("extensions.abprime.defaulttoolbaraction", 0);
pref("extensions.abprime.defaultstatusbaraction", 0);
pref("extensions.abprime.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.abprime.sendReport_key", "");
pref("extensions.abprime.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.abprime.enable_key", "");
pref("extensions.abprime.flash_scrolltoitem", true);
pref("extensions.abprime.previewimages", true);
pref("extensions.abprime.data_directory", "adblockplus");
pref("extensions.abprime.patternsbackups", 5);
pref("extensions.abprime.patternsbackupinterval", 24);
pref("extensions.abprime.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.abprime.hideimagemanager", true);
pref("extensions.abprime.subscriptions_autoupdate", true);
pref("extensions.abprime.subscriptions_listurl", "https://adblockplus.org/subscriptions2.xml");
pref("extensions.abprime.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.abprime.subscriptions_fallbackerrors", 5);
pref("extensions.abprime.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.abprime.savestats", true);
pref("extensions.abprime.composer_default", 2);
pref("extensions.abprime.clearStatsOnHistoryPurge", true);
pref("extensions.abprime.report_submiturl", "");
pref("extensions.abprime.recentReports", "[]");
pref("services.sync.engine.abprime", false);
