#!/bin/bash

if which sha256sum &>/dev/null; then
	sha256sum "$1" | grep -Eo '^[a-f0-9]{64}'
elif which openssl &>/dev/null; then
	openssl dgst -sha256 "$1" | grep -Eo '[a-f0-9]{64}$'
elif which whash &>/dev/null; then
	whash -sha256 "$1"
else
	echo "Unable to find a program to calculate SHA256 hashes."
	exit 1
fi
