

pref("extensions.adblocklatitude.currentVersion", "0.0");
pref("extensions.adblocklatitude.enabled", true);
pref("extensions.adblocklatitude.frameobjects", true);
pref("extensions.adblocklatitude.fastcollapse", false);
pref("extensions.adblocklatitude.showinstatusbar", false);
pref("extensions.adblocklatitude.detachsidebar", false);
pref("extensions.adblocklatitude.defaulttoolbaraction", 0);
pref("extensions.adblocklatitude.defaultstatusbaraction", 0);
pref("extensions.adblocklatitude.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.adblocklatitude.sendReport_key", "");
pref("extensions.adblocklatitude.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.adblocklatitude.enable_key", "");
pref("extensions.adblocklatitude.flash_scrolltoitem", true);
pref("extensions.adblocklatitude.previewimages", true);
pref("extensions.adblocklatitude.data_directory", "adblockplus");
pref("extensions.adblocklatitude.patternsbackups", 5);
pref("extensions.adblocklatitude.patternsbackupinterval", 24);
pref("extensions.adblocklatitude.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.adblocklatitude.hideimagemanager", true);
pref("extensions.adblocklatitude.subscriptions_autoupdate", true);
pref("extensions.adblocklatitude.subscriptions_listurl", "https://adblockplus.org/subscriptions2.xml");
pref("extensions.adblocklatitude.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.adblocklatitude.subscriptions_fallbackerrors", 5);
pref("extensions.adblocklatitude.subscriptions_exceptionsurl", "");
pref("extensions.adblocklatitude.subscriptions_exceptionscheckbox", false);
pref("extensions.adblocklatitude.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.adblocklatitude.savestats", true);
pref("extensions.adblocklatitude.composer_default", 2);
pref("extensions.adblocklatitude.clearStatsOnHistoryPurge", true);
pref("extensions.adblocklatitude.report_submiturl", "");
pref("extensions.adblocklatitude.recentReports", "[]");
pref("services.sync.engine.adblocklatitude", false);
